---
# MySQL setup

- hosts: crispr-exposed
  user: root

  vars_files:
    - vars.yml

  vars_prompt:

    - name: mysql_root_password
      prompt: "Enter password for mysql root user"
      private: yes
      confirm: yes
    
    - name: mysql_crispr_passwd
      prompt: "Enter mysql crispr user"
      private: yes
      confirm: yes

  tasks:

    # Secure setup
    - name: MySQL_Secure | Start the MySQL service
      service: 
        name: mysql 
        state: started
        enabled: true

    - name: MySQL_Secure | update mysql root password for all root accounts
      mysql_user: 
        name: root 
        host: "{{ item }}" 
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost 

    - name: MySQL_Secure | Configuration file, edit my.cnf
      shell: echo '[client]' > /root/.my.cnf && echo 'user=root' >> /root/.my.cnf && echo 'password={{ mysql_root_password }}'>> /root/.my.cnf

    - name: MySQL_Secure | Delete anonymous MySQL server user
      mysql_user: user="" host="{{ hostname }}" state="absent"
      
    - name: MySQL_Secure | Delete anonymous MySQL server user for localhost
      mysql_user: user="" state="absent"
  
    - name: MySQL_Secure | Secure the MySQL root user for IPV6 localhost (::1)
      mysql_user: user="root" password="{{ mysql_root_password }}" host="::1"

    - name: MySQL_Secure | Secure the MySQL root user for IPV4 localhost (127.0.0.1)
      mysql_user: user="root" password="{{ mysql_root_password }}" host="127.0.0.1"
  
    - name: MySQL_Secure | Secure the MySQL root user for localhost domain (localhost)
      mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ hostname }}"

    - name: MySQL_Secure | Secure the MySQL root user for {{ server_hostname }} domain
      mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ hostname }}"
  
    - name: MySQL_Secure | Remove the MySQL test database
      mysql_db: db=test state=absent

    # Custom setup
    - name: MySQL | create crispr db
      mysql_db: name="{{ mysql_crispr_db }}" state=present
    
    - name: MySQL | create crispr user.
      mysql_user: >
        user="{{ mysql_crispr_user }}" 
        password="{{ mysql_crispr_passwd }}" 
        host="{{ hostname }}" 
        priv="{{ mysql_crispr_db }}".*:ALL state=present
    
    - name: MySQL | Restart MySQL
      service: name=mysql state=restarted
    
    