---
- name: Webserver | Setup
  hosts: crispr-exposed
  user: root
  
  tasks:
    - name: Webserver | update apt cache
      apt: update_cache=yes

    - name: Webserver | Install packages
      apt: pkg={{item}} state=installed
      with_items: 
        - apache2
        - libapache2-mod-wsgi-py3

    - name: Webserver | vhost file
      template: >
        src=../templates/000-default.conf 
        dest=/etc/apache2/sites-enabled/
        backup=yes

    - name: Webserver | log file location
      file: >
        path="/var/log/django" 
        state=directory 
        owner=www-data
        group=www-data
        mode=0755

    - name: Webserver | Restart Apache2
      service: name=apache2 state=restarted
    